# Generated by Django 4.2.1 on 2023-05-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_cms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=250)),
                ('title', models.TextField(verbose_name=200)),
                ('img', models.TextField(verbose_name=250)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=250)),
                ('LastName', models.TextField(max_length=250)),
                ('Profession', models.TextField(max_length=250)),
                ('Description', models.TextField(max_length=250)),
                ('profilePicture', models.TextField(max_length=255)),
                ('curriculumVitae', models.TextField(max_length=255)),
            ],
        ),
    ]
